config/routes.rb
Rails.application.routes.draw do
  # namespace :nasas do
  #   get 'apod/display'
  # end
  # namespace :nasa do
  #   get 'apod/display'
  # end
  resources :nasas

  resources :users
  resources :searches do
    end
  

get '/apod', to: "nasas#apod"

  match ':controller(/:action(/:id))', :via => :get
  #match 'welcome/index', to: 'welcome:show', via: :all
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/nasa.rb
class Nasa < ApplicationRecord
end

app/controllers/nasas_controller.rb
class NasasController < ApplicationController
  before_action :set_nasa, only: [:show, :edit, :update, :destroy]

  # GET /nasas
  # GET /nasas.json
  def index
    @nasas = Nasa.all
  end

  # GET /nasas/1
  # GET /nasas/1.json
  def show
  end

  # GET /nasas/new
  def new
    @nasa = Nasa.new
  end

  # GET /nasas/1/edit
  def edit
  end

  # POST /nasas
  # POST /nasas.json
  def create
    @nasa = Nasa.new(nasa_params)

    respond_to do |format|
      if @nasa.save
        format.html { redirect_to @nasa, notice: 'Nasa was successfully created.' }
        format.json { render :show, status: :created, location: @nasa }
      else
        format.html { render :new }
        format.json { render json: @nasa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nasas/1
  # PATCH/PUT /nasas/1.json
  def update
    respond_to do |format|
      if @nasa.update(nasa_params)
        format.html { redirect_to @nasa, notice: 'Nasa was successfully updated.' }
        format.json { render :show, status: :ok, location: @nasa }
      else
        format.html { render :edit }
        format.json { render json: @nasa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nasas/1
  # DELETE /nasas/1.json
  def destroy
    @nasa.destroy
    respond_to do |format|
      format.html { redirect_to nasas_url, notice: 'Nasa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
def apod
    
    @json_string = Apod.result()
@picture_url = Apod.url()
    
respond_to do |format|
      
      format.html { render :apod}
      format.json { render :apod, json: @json_string.to_json }
format.json { render :apod, json: @picture_url.to_json }
    
end
  
end
  
private
  # Use callbacks to share common setup or constraints between actions.
  def set_nasa
    @nasa = Nasa.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def nasa_params
    params.require(:nasa).permit(:api, :url)
  end
end

app/helpers/nasas/apod_helper.rb
module Nasas::ApodHelper
end

app/helpers/nasas_helper.rb
module NasasHelper
end

app/views/nasas/_form.html.erb
<%= form_with(model: nasa, local: true) do |form| %>
  <% if nasa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(nasa.errors.count, "error") %> prohibited this nasa from being saved:</h2>

      <ul>
      <% nasa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :api %>
    <%= form.text_field :api %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/nasas/apod.html.erb
<h1> Astronomy Picture of the Day (APOD) microservice </h1>

<b>Title:</b>
<style>
h2 { color: blue; text-indent: 10px;}
</style>
<h2> 
<%= "    \"#{@json_string[0]["title"]} \" " %>
</h2>
<b>Description:</b>
<br>
<%= "#{@json_string[0]["explanation"]}" %>


<%= image_tag("#{@json_string[0]['url']}", draggable: "true", id: "drag1") %>

app/views/nasas/edit.html.erb
<h1>Editing Nasa</h1>

<%= render 'form', nasa: @nasa %>

<%= link_to 'Show', @nasa %> |
<%= link_to 'Back', nasas_path %>

app/views/nasas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>NASA APIs</h1>


<br>

<!--%= link_to 'New Nasa', new_nasa_path %-->

<h3>  <%= link_to 'APOD', {:controller => 'nasas', :action => 'apod'} %> -  Astronomy Picture of the Day</h3>

app/views/nasas/new.html.erb
<h1>New Nasa</h1>

<%= render 'form', nasa: @nasa %>

<%= link_to 'Back', nasas_path %>

app/views/nasas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Api:</strong>
  <%= @nasa.api %>
</p>

<p>
  <strong>Url:</strong>
  <%= @nasa.url %>
</p>

<%= link_to 'Edit', edit_nasa_path(@nasa) %> |
<%= link_to 'Back', nasas_path %>