config/routes.rb
Rails.application.routes.draw do
  # namespace :nasas do
  #   get 'apod/display'
  # end
  # namespace :nasa do
  #   get 'apod/display'
  # end
  resources :nasas

  resources :users
  resources :searches do
    end
  

get '/apod', to: "nasas#apod"

  match ':controller(/:action(/:id))', :via => :get
  #match 'welcome/index', to: 'welcome:show', via: :all
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/search.rb
class Search < ApplicationRecord
  has_many :widgets
  accepts_nested_attributes_for :widgets

  ConfigHelper.load()
  
  API_KEY = ENV["YELP_API_KEY"]

  # Constants, do not change these
  API_HOST = "https://api.yelp.com"
  SEARCH_PATH = "/v3/businesses/search"
  BUSINESS_PATH = "/v3/businesses/"  # trailing / because we append the business id to the path
  
  
  DEFAULT_BUSINESS_ID = "yelp-san-francisco"
  DEFAULT_TERM = "dinner"
  DEFAULT_LOCATION = "San Francisco, CA"
  SEARCH_LIMIT = 5
        
  # Returns a parsed json object of the request
  def self.result(term, location)
    url = "#{API_HOST}#{SEARCH_PATH}"
    params = {
      term: term,
      location: location,
      limit: SEARCH_LIMIT
    }

    # append to empty array then return names once built
    the_arr = []
    response = HTTP.auth("Bearer #{API_KEY}").get(url, params: params)
    the_json = response.parse["businesses"]
    the_json.each do |f|
      the_arr << f["name"]
    end
    return the_arr
  end

  def self.yelpurl(term, location)

    url = "#{API_HOST}#{SEARCH_PATH}"
    params = {
      term: term,
      location: location,
      limit: SEARCH_LIMIT
    }

    response = HTTP.auth("Bearer #{API_KEY}").get(url, params: params)
    response.parse["businesses"]
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  before_action :set_search, only: [:show, :edit, :update, :destroy]
  
  DEFAULT_TERM = "burgers"
  DEFAULT_LOCATION = "San Francisco, CA"



  # GET /searches
  # GET /searches.json
  def index
    @searches = Search.all
  end

  # GET /searches/1
  # GET /searches/1.json
  def show
    #@location = DEFAULT_LOCATION
    #@term =  @search.search
   # @searches = @search.search(DEFAULT_TERM,DEFAULT_LOCATION)
    # @search.search(DEFAULT_TERM,DEFAULT_LOCATION)
    #@yelpjson = SearchesHelper.result(DEFAULT_TERM, DEFAULT_LOCATION)
    # render :json => @yelpjson.to_json
    #@yelpjson = Search.all
    @yelp_url = Search.yelpurl(@search.search,DEFAULT_LOCATION)

    respond_to do |format|
      # format.html { render :show}
      # format.json { render :show, json: @yelpjson.to_json }
        format.html { render :show}
        format.json { render :show, json: @yelp_url.to_json }

  end

  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:search).permit(:search)
    end
end

app/helpers/searches_helper.rb
require "http"
module SearchesHelper
  config_files = ['secrets.yml']

  config_files.each do |file_name|
    file_path = File.join(Rails.root, 'config', file_name)
    config_keys = HashWithIndifferentAccess.new(YAML::load(IO.read(file_path)))[Rails.env]
    config_keys.each do |k,v|
      ENV[k.upcase] ||= v
    end
  end

  API_KEY = ENV["YELP_API_KEY"]


  # Constants, do not change these
  API_HOST = "https://api.yelp.com"
  SEARCH_PATH = "/v3/businesses/search"
  BUSINESS_PATH = "/v3/businesses/"  # trailing / because we append the business id to the path
  
  
  DEFAULT_BUSINESS_ID = "yelp-san-francisco"
  DEFAULT_TERM = "dinner"
  DEFAULT_LOCATION = "San Francisco, CA"
  SEARCH_LIMIT = 5
    
  # Returns a parsed json object of the request
  def self.result(term, location)
    url = "#{API_HOST}#{SEARCH_PATH}"
    params = {
      term: term,
      location: location,
      limit: SEARCH_LIMIT
    }

    response = HTTP.auth("Bearer #{API_KEY}").get(url, params: params)
    response.parse
  end

  # Returns a parsed json object of the request
  def business(business_id)
    url = "#{API_HOST}#{BUSINESS_PATH}#{business_id}"

    response = HTTP.auth("Bearer #{API_KEY}").get(url)
    response.parse
  end

end

app/views/searches/_form.html.erb
<%= form_with(model: search, local: true) do |form| %>
  <% if search.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search.errors.count, "error") %> prohibited this search from being saved:</h2>

      <ul>
      <% search.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
    <%= form.label :search %>
    <%= form.text_field :search %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<% provide(:title, "Yelp Searches") %>
<p id="notice"><%= notice %></p>

<h1>Yelp Searches</h1>

<table>
  <thead>
    <tr>
      <th>Searches made to Yelp </th>

    </tr>
  </thead>

  <tbody>
    <% @searches.each do |search| %>
      <tr>
        <td><%= search.search %></td>
        <td><%= link_to 'Show', search %></td>
        <td><%= link_to 'Edit', edit_search_path(search) %></td>
        <td><%= link_to 'Destroy', search, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Yelp Search', new_search_path %>
<br>

app/views/searches/new.html.erb
<h1>New Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>


<h1> Yelp Searches </h1>
<br>
<p>
  <strong>Search:</strong>
  <%= @search.search %>
</p>
<br>
<b>Results:</b>
<style>
h2 { color: blue; text-indent: 10px;}
</style>


<% @yelp_url.each do |n| %>

<h2> 
<%= link_to n["name"], n["url"] %>
</h2>
<b> Rating:</b>
<%= "#{n["rating"]}" %>
<br>
<b>Location:</b> 
<%= "#{n["location"]}" %>
<br>
<b>Phone:</b> 
<%= "#{n["display_phone"]}" %>
<br>
<b>Url:</b> 
<%= link_to n["name"], n["url"] %>
<br>
<%= image_tag("#{n['image_url']}", draggable: "true", id: "drag1") %>
<br>
<%end%>
<br>


<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>